name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main  # This will trigger deployment when changes are pushed to the 'main' branch

jobs:
  build-and-deploy:
    name: Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use the Node.js version required by your project

      # Step 3: Install Firebase Tools
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # Step 4: Deploy to Firebase Hosting only
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
